apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project
  type: NodePort 
  ports:
    - protocol: TCP
      port: 3031
      targetPort: 3031
      nodePort: 30000
