apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  type: NodePort 
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30000
